version: "3"
services:
  server:
    build: .
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      - SERVER_PORT=$SERVER_PORT
      - JWT_DOMAIN=$JWT_DOMAIN
      - JWT_ISSUER=$JWT_ISSUER
      - JWT_AUDIENCE=$JWT_AUDIENCE
      - JWT_REALM=$JWT_REALM
      - JWT_SECRET=$JWT_SECRET
      - MONGO_CONNECTION_STRING=$MONGO_CONNECTION_STRING
    depends_on:
      - db
    networks:
      - mongo
    restart: always

  db:
    image: ${MONGO_VERSION}
    ports:
      - "27017:27017"
    volumes:
      - ./localvolumes/mongo:/data/db
    networks:
      - mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=adminadmin
    restart: always


networks:
  mongo:
    driver: bridge