version: "3"
services:
  server:
    build: .
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      - db
    networks:
      - mongo
    restart: always
    environment:
      - SERVER_PORT=${SERVER_PORT}

  db:
    image: ${MONGO_VERSION}
    ports:
      - "27017:27017"
    volumes:
      - ./localvolumes/mongo:/data/db
    networks:
      - mongo
    restart: always


networks:
  mongo:
    driver: bridge