version: "3"
services:
  server:
    build: .
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      - ./secretsanta-firebase-adminsdk.json:/secretsanta-key.json
      - ./files:/files
    environment:
      - SERVER_PORT=$SERVER_PORT
      - DATABASE_CONNECTION_STRING=$DATABASE_CONNECTION_STRING
      - POSTGRES_NAME=$POSTGRES_NAME
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - GOOGLE_APPLICATION_CREDENTIALS=$GOOGLE_APPLICATION_CREDENTIALS
      - JWT_SECRET=$JWT_SECRET
      - JWT_AUDIENCE=$JWT_AUDIENCE
      - JWT_ISSUER=$JWT_ISSUER
      - JWT_ACCESS_LIFETIME=$JWT_ACCESS_LIFETIME
      - JWT_REFRESH_LIFETIME=$JWT_REFRESH_LIFETIME
      - ONESIGNAL_API_KEY=$ONESIGNAL_API_KEY
    depends_on:
      - db
    networks:
      - db_network
      - prometheus_network
    restart: always

  db:
    image: ${POSTGRES_IMAGE}
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "santa"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - ./db-data:/var/lib/postgresql/data
      - ./sql/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - db_network
    restart: always

  # Prometheus container to query backend metrics
  prometheus:
    image: prom/prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring:/etc/prometheus/
    networks:
      - prometheus_network

      # Grafana container to visualize data
  grafana:
    image: grafana/grafana:5.1.0
    ports:
      - "3000:3000"
    volumes:
      - ./monitoring/grafana:/var/lib/grafana
    networks:
      - prometheus_network


networks:
  db_network:
    driver: bridge
  prometheus_network:
    driver: bridge