version: "3"
services:
  server:
    build: .
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      - ./secretsanta-firebase-adminsdk.json:/secretsanta-key.json
      - ./files:/files
    environment:
      - SERVER_PORT=$SERVER_PORT
      - DATABASE_CONNECTION_STRING=$DATABASE_CONNECTION_STRING
      - POSTGRES_NAME=$POSTGRES_NAME
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - GOOGLE_APPLICATION_CREDENTIALS=$GOOGLE_APPLICATION_CREDENTIALS
      - JWT_SECRET=$JWT_SECRET
      - JWT_AUDIENCE=$JWT_AUDIENCE
      - JWT_ISSUER=$JWT_ISSUER
      - JWT_ACCESS_LIFETIME=$JWT_ACCESS_LIFETIME
      - JWT_REFRESH_LIFETIME=$JWT_REFRESH_LIFETIME
    depends_on:
      - db
    networks:
      - db_network
    restart: always

  db:
    image: ${POSTGRES_IMAGE}
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "santa"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - ./db-data:/var/lib/postgresql/data
      - ./sql/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - db_network
    restart: always

networks:
  db_network:
    driver: bridge